name: first-workflow
run-name: Ubuntu Workflow on Main

on: 
  - push

jobs: 
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Hello World
              run: echo "Hello World"